version: "3"

services:
  api:
    build:
      context: .
    env_file: 
      - ./.env
    environment: 
      - GORM_CONNECTION_DSN=postgresql://mmc:dbpasswd@postgres:5432/mmc?sslmode=disable
    ports:
      - "${API_PORT:-3001}:3001"
    networks: 
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
       - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
